name: 'Basic'

on: push

jobs:
  first:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        node: [ '16.x', '18.x' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Say Hello from OS - ${{ matrix.os }}
      shell: bash
      run: |
        echo "Hello World from ${{ matrix.os }}"
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{ matrix.node }}'
    - name: Run only on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        echo "Hello from ${{ matrix.os }}"